import type { VariantConfig } from './types'

/** Production homepage — Timeline layout */
export const primaryVariantSlug = 'v22'

export const variants: VariantConfig[] = [
  {
    id: 1,
    slug: 'v1',
    name: 'Linear',
    tagline: 'Refined dark with red mesh glow',
    accent: 'red',
    heroLayout: 'centered',
    featureLayout: 'grid',
    navStyle: 'glass',
    buttonStyle: 'pill',
    shell: 'bg-black text-zinc-100',
    showGrid: true,
    showNoise: true,
    showMesh: true,
    radius: 'xl',
  },
  {
    id: 2,
    slug: 'v2',
    name: 'Cursor',
    tagline: 'Terminal green on pure black',
    accent: 'emerald',
    heroLayout: 'centered',
    featureLayout: 'list',
    navStyle: 'bordered',
    buttonStyle: 'square',
    shell: 'bg-black text-zinc-100',
    font: 'mono',
    showGrid: false,
    showNoise: true,
    radius: 'md',
  },
  {
    id: 3,
    slug: 'v3',
    name: 'Vercel',
    tagline: 'Sharp monochrome precision',
    accent: 'white',
    heroLayout: 'centered',
    featureLayout: 'compact',
    navStyle: 'minimal',
    buttonStyle: 'square',
    shell: 'bg-black text-white',
    showGrid: true,
    radius: 'md',
  },
  {
    id: 4,
    slug: 'v4',
    name: 'Apple',
    tagline: 'Large calm typography',
    accent: 'white',
    heroLayout: 'centered',
    featureLayout: 'grid',
    navStyle: 'glass',
    buttonStyle: 'pill',
    shell: 'bg-zinc-950 text-zinc-100',
    backdrop: 'bg-[radial-gradient(ellipse_at_top,rgba(255,255,255,0.06),transparent_50%)]',
    radius: 'full',
  },
  {
    id: 5,
    slug: 'v5',
    name: 'Brutalist',
    tagline: 'Hard edges, loud contrast',
    accent: 'white',
    heroLayout: 'split',
    featureLayout: 'list',
    navStyle: 'bordered',
    buttonStyle: 'square',
    shell: 'bg-black text-white',
    radius: 'none',
  },
  {
    id: 6,
    slug: 'v6',
    name: 'Aurora',
    tagline: 'Violet and blue gradients',
    accent: 'violet',
    heroLayout: 'centered',
    featureLayout: 'bento',
    navStyle: 'glass',
    buttonStyle: 'pill',
    shell: 'bg-[#050508] text-zinc-100',
    backdrop: 'bg-[radial-gradient(circle_at_20%_0%,rgba(139,92,246,0.25),transparent_40%),radial-gradient(circle_at_80%_20%,rgba(59,130,246,0.15),transparent_35%)]',
    showMesh: true,
    radius: 'xl',
  },
  {
    id: 7,
    slug: 'v7',
    name: 'Glass',
    tagline: 'Heavy frosted surfaces',
    accent: 'blue',
    heroLayout: 'centered',
    featureLayout: 'grid',
    navStyle: 'floating',
    buttonStyle: 'pill',
    shell: 'bg-[#030712] text-zinc-100',
    backdrop: 'bg-[radial-gradient(ellipse_at_center,rgba(59,130,246,0.12),transparent_60%)]',
    radius: 'xl',
  },
  {
    id: 8,
    slug: 'v8',
    name: 'Monochrome',
    tagline: 'Typography-only elegance',
    accent: 'white',
    heroLayout: 'minimal',
    featureLayout: 'compact',
    navStyle: 'minimal',
    buttonStyle: 'ghost',
    shell: 'bg-black text-zinc-300',
    radius: 'none',
  },
  {
    id: 9,
    slug: 'v9',
    name: 'Ink Red',
    tagline: 'Bold brand-forward energy',
    accent: 'red',
    heroLayout: 'centered',
    featureLayout: 'grid',
    navStyle: 'bordered',
    buttonStyle: 'pill',
    shell: 'bg-[#0a0000] text-zinc-100',
    backdrop: 'bg-[radial-gradient(circle_at_50%_0%,rgba(255,75,75,0.35),transparent_55%)]',
    showMesh: true,
    radius: 'xl',
  },
  {
    id: 10,
    slug: 'v10',
    name: 'Neon',
    tagline: 'Cyber cyan accents',
    accent: 'cyan',
    heroLayout: 'split',
    featureLayout: 'bento',
    navStyle: 'glass',
    buttonStyle: 'square',
    shell: 'bg-[#000810] text-zinc-100',
    backdrop: 'bg-[radial-gradient(circle_at_70%_10%,rgba(34,211,238,0.2),transparent_40%)]',
    radius: 'md',
  },
  {
    id: 11,
    slug: 'v11',
    name: 'Editorial',
    tagline: 'Magazine-style hierarchy',
    accent: 'amber',
    heroLayout: 'centered',
    featureLayout: 'list',
    navStyle: 'minimal',
    buttonStyle: 'ghost',
    shell: 'bg-[#0c0c0c] text-stone-200',
    font: 'mixed',
    radius: 'none',
  },
  {
    id: 12,
    slug: 'v12',
    name: 'Split',
    tagline: 'Copy left, panel right',
    accent: 'red',
    heroLayout: 'split',
    featureLayout: 'grid',
    navStyle: 'glass',
    buttonStyle: 'pill',
    shell: 'bg-black text-zinc-100',
    showGrid: true,
    radius: 'xl',
  },
  {
    id: 13,
    slug: 'v13',
    name: 'Bento',
    tagline: 'Asymmetric feature tiles',
    accent: 'blue',
    heroLayout: 'centered',
    featureLayout: 'bento',
    navStyle: 'floating',
    buttonStyle: 'pill',
    shell: 'bg-zinc-950 text-zinc-100',
    showNoise: true,
    radius: 'xl',
  },
  {
    id: 14,
    slug: 'v14',
    name: 'Blueprint',
    tagline: 'Visible grid crosshairs',
    accent: 'blue',
    heroLayout: 'centered',
    featureLayout: 'grid',
    navStyle: 'bordered',
    buttonStyle: 'square',
    shell: 'bg-[#020617] text-blue-100',
    showGrid: true,
    font: 'mono',
    radius: 'md',
  },
  {
    id: 15,
    slug: 'v15',
    name: 'Soft',
    tagline: 'Rounded and gentle',
    accent: 'violet',
    heroLayout: 'centered',
    featureLayout: 'grid',
    navStyle: 'glass',
    buttonStyle: 'pill',
    shell: 'bg-[#0f0f12] text-zinc-200',
    backdrop: 'bg-[radial-gradient(circle_at_50%_120%,rgba(167,139,250,0.12),transparent_50%)]',
    radius: 'full',
  },
  {
    id: 16,
    slug: 'v16',
    name: 'Stripe',
    tagline: 'Diagonal gradient bands',
    accent: 'violet',
    heroLayout: 'centered',
    featureLayout: 'compact',
    navStyle: 'minimal',
    buttonStyle: 'pill',
    shell: 'bg-[#0a0a0f] text-zinc-100',
    backdrop: 'bg-[linear-gradient(135deg,rgba(139,92,246,0.12)_0%,transparent_40%,rgba(59,130,246,0.08)_100%)]',
    radius: 'xl',
  },
  {
    id: 17,
    slug: 'v17',
    name: 'Zen',
    tagline: 'Ultra-minimal whitespace',
    accent: 'white',
    heroLayout: 'minimal',
    featureLayout: 'compact',
    navStyle: 'minimal',
    buttonStyle: 'ghost',
    shell: 'bg-black text-zinc-400',
    radius: 'none',
  },
  {
    id: 18,
    slug: 'v18',
    name: 'Command',
    tagline: 'Palette-inspired UI',
    accent: 'emerald',
    heroLayout: 'spotlight',
    featureLayout: 'list',
    navStyle: 'bordered',
    buttonStyle: 'square',
    shell: 'bg-[#0a0f0a] text-zinc-100',
    font: 'mono',
    radius: 'md',
  },
  {
    id: 19,
    slug: 'v19',
    name: 'Spotlight',
    tagline: 'Search-bar hero metaphor',
    accent: 'white',
    heroLayout: 'spotlight',
    featureLayout: 'grid',
    navStyle: 'glass',
    buttonStyle: 'pill',
    shell: 'bg-black text-zinc-100',
    showGrid: true,
    radius: 'full',
  },
  {
    id: 20,
    slug: 'v20',
    name: 'Matrix',
    tagline: 'Dot texture field',
    accent: 'emerald',
    heroLayout: 'centered',
    featureLayout: 'grid',
    navStyle: 'glass',
    buttonStyle: 'square',
    shell: 'bg-black text-emerald-50',
    backdrop: 'bg-[radial-gradient(circle,rgba(52,211,153,0.15)_1px,transparent_1px)] bg-[length:24px_24px]',
    font: 'mono',
    radius: 'md',
  },
  {
    id: 21,
    slug: 'v21',
    name: 'Premium First',
    tagline: 'Pricing-led hero',
    accent: 'gold',
    heroLayout: 'pricing-first',
    featureLayout: 'compact',
    navStyle: 'floating',
    buttonStyle: 'pill',
    shell: 'bg-[#0a0800] text-stone-100',
    backdrop: 'bg-[radial-gradient(circle_at_50%_0%,rgba(234,179,8,0.15),transparent_50%)]',
    radius: 'xl',
  },
  {
    id: 22,
    slug: 'v22',
    name: 'Timeline',
    tagline: 'Process-forward layout',
    accent: 'red',
    heroLayout: 'centered',
    featureLayout: 'list',
    navStyle: 'glass',
    buttonStyle: 'pill',
    shell: 'bg-black text-zinc-100',
    showNoise: true,
    radius: 'xl',
  },
  {
    id: 23,
    slug: 'v23',
    name: 'Geometric',
    tagline: 'Angular sharp layout',
    accent: 'cyan',
    heroLayout: 'split',
    featureLayout: 'bento',
    navStyle: 'bordered',
    buttonStyle: 'square',
    shell: 'bg-[#001018] text-cyan-50',
    radius: 'none',
  },
  {
    id: 24,
    slug: 'v24',
    name: 'Frost',
    tagline: 'Ice-white frost overlay',
    accent: 'white',
    heroLayout: 'centered',
    featureLayout: 'grid',
    navStyle: 'floating',
    buttonStyle: 'pill',
    shell: 'bg-[#08090c] text-zinc-100',
    backdrop: 'bg-[radial-gradient(ellipse_at_top,rgba(255,255,255,0.08),transparent_60%)]',
    showNoise: true,
    radius: 'xl',
  },
  {
    id: 25,
    slug: 'v25',
    name: 'Ultra Luxury',
    tagline: 'Gold premium finish',
    accent: 'gold',
    heroLayout: 'centered',
    featureLayout: 'grid',
    navStyle: 'glass',
    buttonStyle: 'pill',
    shell: 'bg-[#050505] text-stone-100',
    backdrop: 'bg-[radial-gradient(ellipse_at_50%_-20%,rgba(250,204,21,0.18),transparent_55%)]',
    showMesh: true,
    radius: 'full',
  },
]

export function getVariant(slug: string): VariantConfig | undefined {
  return variants.find((v) => v.slug === slug)
}
