import Foundation
import AppKit
import Combine
import os

/// Abstraction over the system pasteboard so tests can drive change counts,
/// advertised types, and string contents without touching `NSPasteboard.general`.
protocol PasteboardProviding: AnyObject {
    var changeCount: Int { get }
    func types() -> [NSPasteboard.PasteboardType]?
    func readString() -> String?
    func writeString(_ string: String)   // clearContents + setString(.string)
}

/// Production adapter wrapping `NSPasteboard.general`.
final class SystemPasteboard: PasteboardProviding {
    private let pasteboard: NSPasteboard

    init(pasteboard: NSPasteboard = .general) {
        self.pasteboard = pasteboard
    }

    var changeCount: Int {
        pasteboard.changeCount
    }

    func types() -> [NSPasteboard.PasteboardType]? {
        pasteboard.types
    }

    func readString() -> String? {
        pasteboard.string(forType: .string)
    }

    func writeString(_ string: String) {
        pasteboard.clearContents()
        pasteboard.setString(string, forType: .string)
    }
}

/// Single source of truth for the lightweight clipboard history.
/// Mirrors `NoteStore`'s dependency-injection style: an injectable pasteboard,
/// storage URL, and cap so tests run without the real system pasteboard or
/// real Library directory.
@MainActor
final class ClipboardHistoryStore: ObservableObject {
    /// Newest first, capped at `maxEntries`.
    @Published private(set) var entries: [ClipEntry] = []

    private let pasteboard: PasteboardProviding
    private let storageURL: URL
    private let maxEntries: Int
    private let fileManager: FileManager

    private var lastSeenChangeCount: Int
    private var timer: Timer?

    private static let logger = Logger(subsystem: "com.jonasbubela.Ink", category: "ClipboardHistoryStore")
    private static let pollInterval: TimeInterval = 0.5

    /// Pasteboard types that signal concealed/transient/sensitive content.
    /// If any are advertised we skip without reading the value (favor privacy).
    private static let privacyTypes: Set<NSPasteboard.PasteboardType> = [
        NSPasteboard.PasteboardType("org.nspasteboard.ConcealedType"),
        NSPasteboard.PasteboardType("org.nspasteboard.TransientType"),
        NSPasteboard.PasteboardType("org.nspasteboard.AutoGeneratedType"),
        NSPasteboard.PasteboardType("com.apple.is-sensitive")
    ]

    /// Application Support/Ink directory — derived independently of the user's
    /// chosen notes folder (sibling of `Notes/`, not inside it).
    static var defaultStorageURL: URL {
        let appSupport = FileManager.default.urls(for: .applicationSupportDirectory, in: .userDomainMask).first!
        return appSupport.appendingPathComponent("Ink/clipboard-history.json", isDirectory: false)
    }

    init(
        pasteboard: PasteboardProviding = SystemPasteboard(),
        storageURL: URL? = nil,
        maxEntries: Int = 25,
        fileManager: FileManager = .default
    ) {
        self.pasteboard = pasteboard
        self.storageURL = storageURL ?? Self.defaultStorageURL
        self.maxEntries = maxEntries
        self.fileManager = fileManager
        self.lastSeenChangeCount = pasteboard.changeCount

        load()
    }

    // MARK: - Monitoring

    /// Begin polling the pasteboard. Safe to call once from
    /// `AppDelegate.applicationDidFinishLaunching`.
    func start() {
        guard timer == nil else { return }

        let timer = Timer(timeInterval: Self.pollInterval, repeats: true) { [weak self] _ in
            Task { @MainActor in
                self?.checkForChanges()
            }
        }
        // `.common` mode keeps the poll alive while menus/tracking loops run.
        RunLoop.main.add(timer, forMode: .common)
        self.timer = timer
    }

    func stop() {
        timer?.invalidate()
        timer = nil
    }

    /// Inspect the pasteboard and ingest a new plain-text copy if appropriate.
    /// A normal method so tests can drive ingestion directly (no Timer needed).
    func checkForChanges() {
        let currentCount = pasteboard.changeCount
        guard currentCount != lastSeenChangeCount else { return }
        lastSeenChangeCount = currentCount

        // Privacy: skip concealed/transient/sensitive items without reading.
        if let advertised = pasteboard.types(),
           advertised.contains(where: { Self.privacyTypes.contains($0) }) {
            return
        }

        guard let raw = pasteboard.readString() else { return }
        guard !raw.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty else { return }

        ingest(text: raw)
    }

    // MARK: - Reuse / Clear

    /// Copy an entry's text back to the system clipboard and move it to the top.
    func copyToClipboard(_ entry: ClipEntry) {
        pasteboard.writeString(entry.text)
        // Avoid re-ingesting our own write on the next poll tick.
        lastSeenChangeCount = pasteboard.changeCount

        moveToTop(matching: entry.text, fallback: entry)
        persist()
    }

    /// Empty the history and remove the on-disk file.
    func clearHistory() {
        entries = []
        do {
            try fileManager.removeItem(at: storageURL)
        } catch CocoaError.fileNoSuchFile {
            // Already absent — nothing to do.
        } catch let error as NSError where error.domain == NSCocoaErrorDomain
            && error.code == NSFileNoSuchFileError {
            // Already absent — nothing to do.
        } catch {
            Self.logger.error("Could not remove clipboard history file: \(String(describing: error), privacy: .public)")
        }
    }

    // MARK: - Mutation helpers

    private func ingest(text: String) {
        var updated = entries.filter { $0.text != text }
        let entry = ClipEntry(id: UUID(), text: text, copiedAt: Date())
        updated.insert(entry, at: 0)

        if updated.count > maxEntries {
            updated = Array(updated.prefix(maxEntries))
        }

        entries = updated
        persist()
    }

    /// Move the entry with matching text to the front. If none exists (e.g. it
    /// was capped out), insert the provided fallback at the front instead.
    private func moveToTop(matching text: String, fallback: ClipEntry) {
        if let existing = entries.first(where: { $0.text == text }) {
            var updated = entries.filter { $0.text != text }
            updated.insert(existing, at: 0)
            entries = updated
        } else {
            var updated = entries
            updated.insert(fallback, at: 0)
            if updated.count > maxEntries {
                updated = Array(updated.prefix(maxEntries))
            }
            entries = updated
        }
    }

    // MARK: - Persistence

    private func load() {
        guard fileManager.fileExists(atPath: storageURL.path) else { return }

        do {
            let data = try Data(contentsOf: storageURL)
            let decoded = try JSONDecoder().decode([ClipEntry].self, from: data)
            entries = Array(decoded.prefix(maxEntries))
        } catch {
            // Corrupt/unreadable file → start empty, never crash.
            Self.logger.error("Could not load clipboard history; starting empty: \(String(describing: error), privacy: .public)")
            entries = []
        }
    }

    private func persist() {
        do {
            try fileManager.createDirectory(
                at: storageURL.deletingLastPathComponent(),
                withIntermediateDirectories: true
            )
            let data = try JSONEncoder().encode(entries)
            try data.write(to: storageURL, options: .atomic)
        } catch {
            // In-memory history remains usable even if the write fails.
            Self.logger.error("Could not persist clipboard history: \(String(describing: error), privacy: .public)")
        }
    }
}
