import XCTest
import AppKit
@testable import Ink

/// In-memory fake pasteboard. Tests drive `changeCount`, advertised `types`,
/// and string contents directly; `writeString` bumps `changeCount` to mirror
/// real `NSPasteboard` behavior.
private final class FakePasteboard: PasteboardProviding {
    var changeCount: Int = 0
    var advertisedTypes: [NSPasteboard.PasteboardType]? = [.string]
    var stringContents: String?

    /// Simulate an external copy: set the value and bump the change count.
    func simulateCopy(_ value: String?, types: [NSPasteboard.PasteboardType]? = [.string]) {
        stringContents = value
        advertisedTypes = types
        changeCount += 1
    }

    func types() -> [NSPasteboard.PasteboardType]? {
        advertisedTypes
    }

    func readString() -> String? {
        stringContents
    }

    func writeString(_ string: String) {
        stringContents = string
        advertisedTypes = [.string]
        changeCount += 1
    }
}

final class ClipboardHistoryStoreTests: XCTestCase {
    private var tempRoot: URL!
    private var storageURL: URL!

    override func setUpWithError() throws {
        tempRoot = FileManager.default.temporaryDirectory
            .appendingPathComponent("InkClipTests-\(UUID().uuidString)", isDirectory: true)
        try FileManager.default.createDirectory(at: tempRoot, withIntermediateDirectories: true)
        storageURL = tempRoot.appendingPathComponent("clipboard-history.json", isDirectory: false)
    }

    override func tearDownWithError() throws {
        if let tempRoot {
            try? FileManager.default.removeItem(at: tempRoot)
        }
    }

    @MainActor
    private func makeStore(
        pasteboard: FakePasteboard,
        maxEntries: Int = 25
    ) -> ClipboardHistoryStore {
        ClipboardHistoryStore(
            pasteboard: pasteboard,
            storageURL: storageURL,
            maxEntries: maxEntries
        )
    }

    // 1. New text ingests at the front.
    @MainActor
    func testNewTextIngestsAtFront() throws {
        let pb = FakePasteboard()
        let store = makeStore(pasteboard: pb)

        pb.simulateCopy("hello")
        store.checkForChanges()
        pb.simulateCopy("world")
        store.checkForChanges()

        XCTAssertEqual(store.entries.map(\.text), ["world", "hello"])
    }

    // 2. Duplicate text moves to top, no dup, count stable.
    @MainActor
    func testDuplicateMovesToTopWithoutDuplication() throws {
        let pb = FakePasteboard()
        let store = makeStore(pasteboard: pb)

        for text in ["a", "b", "c"] {
            pb.simulateCopy(text)
            store.checkForChanges()
        }
        XCTAssertEqual(store.entries.map(\.text), ["c", "b", "a"])

        pb.simulateCopy("a")
        store.checkForChanges()

        XCTAssertEqual(store.entries.map(\.text), ["a", "c", "b"])
        XCTAssertEqual(store.entries.count, 3)
    }

    // 3. Cap at maxEntries drops the oldest.
    @MainActor
    func testCapDropsOldest() throws {
        let pb = FakePasteboard()
        let store = makeStore(pasteboard: pb, maxEntries: 3)

        for text in ["1", "2", "3", "4"] {
            pb.simulateCopy(text)
            store.checkForChanges()
        }

        XCTAssertEqual(store.entries.count, 3)
        XCTAssertEqual(store.entries.map(\.text), ["4", "3", "2"])
    }

    // 4. Empty / whitespace-only copies ignored.
    @MainActor
    func testEmptyAndWhitespaceIgnored() throws {
        let pb = FakePasteboard()
        let store = makeStore(pasteboard: pb)

        pb.simulateCopy("")
        store.checkForChanges()
        pb.simulateCopy("   \n\t  ")
        store.checkForChanges()
        pb.simulateCopy(nil)
        store.checkForChanges()

        XCTAssertTrue(store.entries.isEmpty)

        pb.simulateCopy("real")
        store.checkForChanges()
        XCTAssertEqual(store.entries.map(\.text), ["real"])
    }

    // 5. Each concealed/transient/sensitive type is skipped (value never ingested).
    @MainActor
    func testPrivacyTypesSkipped() throws {
        let privacyTypes = [
            "org.nspasteboard.ConcealedType",
            "org.nspasteboard.TransientType",
            "org.nspasteboard.AutoGeneratedType",
            "com.apple.is-sensitive"
        ]

        for rawType in privacyTypes {
            let pb = FakePasteboard()
            let store = makeStore(pasteboard: pb)

            pb.simulateCopy(
                "secret-\(rawType)",
                types: [.string, NSPasteboard.PasteboardType(rawType)]
            )
            store.checkForChanges()

            XCTAssertTrue(
                store.entries.isEmpty,
                "Expected \(rawType) to be skipped, found \(store.entries.map(\.text))"
            )
        }
    }

    // 6. copyToClipboard writes to pasteboard, moves entry to top, and a
    //    following checkForChanges() does NOT create a duplicate.
    @MainActor
    func testCopyToClipboardMovesToTopAndDoesNotReIngest() throws {
        let pb = FakePasteboard()
        let store = makeStore(pasteboard: pb)

        for text in ["x", "y", "z"] {
            pb.simulateCopy(text)
            store.checkForChanges()
        }
        // Newest-first: ["z", "y", "x"]
        let xEntry = try XCTUnwrap(store.entries.first { $0.text == "x" })

        store.copyToClipboard(xEntry)

        XCTAssertEqual(pb.stringContents, "x")
        XCTAssertEqual(store.entries.map(\.text), ["x", "z", "y"])

        // Next poll tick must not re-ingest our own write.
        store.checkForChanges()
        XCTAssertEqual(store.entries.count, 3)
        XCTAssertEqual(store.entries.map(\.text), ["x", "z", "y"])
    }

    // 7. Persistence round-trip: entries reload from disk on a fresh store.
    @MainActor
    func testPersistenceRoundTrip() throws {
        let pb = FakePasteboard()
        let store = makeStore(pasteboard: pb)

        for text in ["one", "two", "three"] {
            pb.simulateCopy(text)
            store.checkForChanges()
        }
        XCTAssertEqual(store.entries.map(\.text), ["three", "two", "one"])

        // Fresh store with the same storageURL should load the same entries.
        let reloaded = ClipboardHistoryStore(
            pasteboard: FakePasteboard(),
            storageURL: storageURL,
            maxEntries: 25
        )
        XCTAssertEqual(reloaded.entries.map(\.text), ["three", "two", "one"])
    }

    // 8. Corrupt JSON file → empty history, no throw.
    @MainActor
    func testCorruptFileYieldsEmptyHistory() throws {
        try "{ not valid json".data(using: .utf8)!.write(to: storageURL)

        let store = makeStore(pasteboard: FakePasteboard())

        XCTAssertTrue(store.entries.isEmpty)
    }

    // 9. clearHistory empties memory and removes the file.
    @MainActor
    func testClearHistoryEmptiesMemoryAndRemovesFile() throws {
        let pb = FakePasteboard()
        let store = makeStore(pasteboard: pb)

        pb.simulateCopy("keep-me")
        store.checkForChanges()
        XCTAssertFalse(store.entries.isEmpty)
        XCTAssertTrue(FileManager.default.fileExists(atPath: storageURL.path))

        store.clearHistory()

        XCTAssertTrue(store.entries.isEmpty)
        XCTAssertFalse(FileManager.default.fileExists(atPath: storageURL.path))

        // Clearing again when the file is already gone must not throw/crash.
        store.clearHistory()
        XCTAssertTrue(store.entries.isEmpty)
    }
}
